baseURL = 'https://blog.depoze.xyz/'
languageCode = 'en-us'
theme = "logseq-hugo-bearblog"
enableRobotsTXT = true

title = "CuSO4_Deposit's Electrolytic Infodump"
author = "CuSO4_Deposit"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Pages"
    url = "/pages/"
    weight = 2
  [[menu.main]]
    name = "Friends"
    url = "/friends/"
    weight = 3
  [[menu.main]]
    name = "Now"
    url = "/now/"
    weight = 4
  [[menu.main]]
    name = "Feed"
    url = '/index.xml'
    weight = 5
